repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        always_run: true  
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: false
        always_run: true  
        types: [python]
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]