repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: [.]
        language: system
        always_run: true
        pass_filenames: false
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        always_run: true
        pass_filenames: false
        types: [python]

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
        